"use server";

import { z } from "zod";
import { redirect } from "next/navigation";
import { revalidatePath } from "next/cache";
import { createClient } from "@/lib/supabase/server";
import { requireActiveUser } from "@/lib/auth";
import { slugify } from "@/lib/utils";
import { parseAndSanitise } from "@/lib/sanitize";
import { isSafeExternalUrl } from "@/lib/url-safety";
import {
  fail,
  fromZod,
  mapDbError,
  type FieldErrors,
} from "@/lib/errors";

const schema = z
  .object({
    topicId: z.string().uuid("Please choose a topic."),
    postType: z.enum(["text", "image", "link", "poll"]),
    title: z
      .string()
      .trim()
      .min(5, "Title must be at least 5 characters.")
      .max(300, "Title must be at most 300 characters."),
    body: z.string().default("{}"),
    bodyText: z.string().default(""),
    linkUrl: z.string().trim().url("Enter a valid URL.").optional().or(z.literal("")),
    imageUrl: z.string().trim().url().optional().or(z.literal("")),
    tags: z.array(z.string()).max(5, "Up to 5 tags.").default([]),
    pollOptions: z.array(z.string().trim().min(1)).default([]),
  })
  .superRefine((v, ctx) => {
    if (v.postType === "link" && !v.linkUrl)
      ctx.addIssue({ code: "custom", message: "A link post needs a URL.", path: ["linkUrl"] });
    if (v.postType === "image" && !v.imageUrl)
      ctx.addIssue({ code: "custom", message: "Please upload an image.", path: ["imageUrl"] });
    if (v.postType === "poll" && v.pollOptions.filter(Boolean).length < 2)
      ctx.addIssue({ code: "custom", message: "A poll needs at least two options.", path: ["pollOptions"] });
    if (v.postType === "text" && v.bodyText.trim().length < 10)
      ctx.addIssue({ code: "custom", message: "Please write at least a sentence.", path: ["body"] });
  });

export type CreatePostState = {
  error?: string;
  fieldErrors?: FieldErrors;
  /** Tag slugs the user picked that we couldn't attach. Surfaced as a
   *  non-fatal notice on the resulting post page. */
  missingTags?: string[];
};

export async function createPost(
  _prev: CreatePostState,
  formData: FormData,
): Promise<CreatePostState> {
  const parsed = schema.safeParse({
    topicId: formData.get("topicId"),
    postType: formData.get("postType"),
    title: formData.get("title"),
    body: formData.get("body") || "{}",
    bodyText: formData.get("bodyText") || "",
    linkUrl: formData.get("linkUrl") || "",
    imageUrl: formData.get("imageUrl") || "",
    tags: formData.getAll("tags").map(String),
    pollOptions: formData.getAll("pollOptions").map(String),
  });
  if (!parsed.success) {
    const f = fromZod(parsed.error);
    return { error: f.error, fieldErrors: f.fieldErrors };
  }

  const v = parsed.data;
  const active = await requireActiveUser();
  if (!active.ok) return { error: active.failure.error };
  if (!active.profile.onboarded) redirect("/onboarding?next=/submit");
  const supabase = await createClient();

  // Validate user-provided URLs against an allowlist (blocks private hosts,
  // non-http schemes, oversized inputs). image_url is generated by our own
  // Supabase storage upload, so we only need to be strict about link_url.
  if (v.linkUrl && !isSafeExternalUrl(v.linkUrl)) {
    return {
      error: "That link isn't allowed. Use a normal https:// URL.",
      fieldErrors: { linkUrl: "Invalid or unsupported URL." },
    };
  }

  const body = parseAndSanitise(v.body);

  const { data: post, error } = await supabase
    .from("posts")
    .insert({
      author_id: active.user.id,
      topic_id: v.topicId,
      title: v.title,
      body,
      body_text: v.bodyText.slice(0, 20000),
      post_type: v.postType,
      link_url: v.linkUrl || null,
      image_url: v.imageUrl || null,
    })
    .select("id")
    .single();

  if (error || !post) {
    if (
      error?.message.includes("check_rate_limit") ||
      error?.code === "42501" ||
      error?.code === "P0001"
    ) {
      const f = fail(
        "rate_limited",
        "You're posting too quickly. Please wait a little while.",
      );
      return { error: f.error };
    }
    const mapped = mapDbError("submit.insert", error ?? { message: "no row" });
    return { error: mapped.error };
  }

  // Tags — find or create, then link. Failures don't block the post but
  // we record which slugs were dropped so the UI can warn the user.
  const tagSlugs = [...new Set(v.tags.map(slugify).filter(Boolean))].slice(0, 5);
  const missingTags: string[] = [];
  if (tagSlugs.length > 0) {
    const { error: tagUpsertErr } = await supabase
      .from("tags")
      .upsert(
        tagSlugs.map((slug) => ({ slug, name: slug })),
        { onConflict: "slug", ignoreDuplicates: true },
      );
    if (tagUpsertErr) {
      console.error("[submit] tag upsert:", tagUpsertErr.message);
      missingTags.push(...tagSlugs);
    } else {
      const { data: tagRows, error: tagSelErr } = await supabase
        .from("tags")
        .select("id, slug")
        .in("slug", tagSlugs);
      if (tagSelErr || !tagRows) {
        console.error("[submit] tag select:", tagSelErr?.message);
        missingTags.push(...tagSlugs);
      } else {
        const foundSlugs = new Set(tagRows.map((t) => t.slug));
        tagSlugs.forEach((s) => {
          if (!foundSlugs.has(s)) missingTags.push(s);
        });
        if (tagRows.length) {
          const { error: linkErr } = await supabase
            .from("post_tags")
            .insert(tagRows.map((t) => ({ post_id: post.id, tag_id: t.id })));
          if (linkErr) {
            console.error("[submit] post_tags insert:", linkErr.message);
            tagRows.forEach((t) => missingTags.push(t.slug));
          }
        }
      }
    }
  }

  // Poll options.
  if (v.postType === "poll") {
    const opts = v.pollOptions.filter(Boolean).slice(0, 6);
    const { error: pollErr } = await supabase.from("poll_options").insert(
      opts.map((label, i) => ({ post_id: post.id, label, sort_order: i })),
    );
    if (pollErr) {
      console.error("[submit] poll_options insert:", pollErr.message);
    }
  }

  // Narrow revalidation — avoid invalidating every home-feed variant on
  // every post; the topic page is the immediate consumer.
  revalidatePath(`/t/${v.topicId}`);
  const suffix = missingTags.length
    ? `?missingTags=${encodeURIComponent(missingTags.join(","))}`
    : "";
  redirect(`/post/${post.id}${suffix}`);
}
